[tool.poetry]
name = "minggu-4"
version = "0.1.0"
description = ""
authors = ["Ahmad Fajar Kusumajati <111202012995@mhs.dinus.ac.id>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
